[package]
name = "nfty"
version = "0.1.0"
authors = ["Naftuli Kay <me@naftuli.wtf>"]
build = "build.rs"

[build-dependencies]
clap = "2.31.2"
structopt = "0.2.6"

[dependencies]
chrono = "0.4.2"
log = "0.4.1"
log4rs = "0.8.0"
log4rs-syslog = "3.0.1"
rayon = "1.0.1"
structopt = "0.2.6"
